### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by yogaajie2** [yogaajie2/porto#1]
### Todo List

- [ ] Fix first Project component already showing in ProjectList (SlideUp not applied)
- [ ] Add SlideUp transitions for other contents
- [ ] Replace template datas in projects.json with **actual** data
- [ ] Run tests
- [ ] Add more...
